### ISSUE TITLE
sqrt function

### ISSUE THREAD

**Issue by sifar21353** [sifar21353/math#1]
import math

math.sqrt(x) will only work when x is a perfect square. Otherwise, the program crashes.

**Comment by sifar21353** [comment]
Will work on making my own square root function tomorrow!

**Comment by sifar21353** [comment]
Made my own square root function!

**Comment by mrunmay-crypto** [comment]
Hi,
I checked math.sqrt(), it is returning a float value even for values like 10 and 2102.

**Comment by sifar21353** [comment]
Oh yes, I just checked and it is returning a float. Has python or the math library received an update?

**Comment by sifar21353** [comment]
Okay, I have understood the problem and came up with a solution!

**Comment by mrunmay-crypto** [comment]
ya probably
